source 'https://rubygems.org'

ruby '3.3.8'

gem 'rails', '~> 8.0'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '>= 6'

gem 'redis'
gem 'redis-namespace'

gem 'bcrypt', '~> 3.1.7'

gem 'bootsnap', '>= 1.4.2', require: false

gem 'rack-cors'

gem 'figaro'
gem 'jwt'

gem 'google-protobuf'
gem 'gtfs-realtime-bindings'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem 'listen'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
